### ISSUE TITLE
Program closes after removal of disabled components.

### ISSUE THREAD

**Issue by MariaPettersson** [Hopsan/hopsan#1789]
Disable components, and remove those.

**Comment by peterNordin** [comment]
I have fond the reason for this crash, it is caused by our use of "gray" color graphics effect applied to the disabled components. I tried this before as well, with locked component, It will not work and I do not know why. We have to find some other way of visualizing disabled component.
It is not even necessary to delete them, just move / hover the mouse and click like cracy can sometimes trigger the crash as well.

**Comment by peterNordin** [comment]
Hmm, just found a possible fix, I put the graphics effect on the mpIcon instead.
Seems to work (tested on Kubuntu) but needs tests in Windows as well @robbr48

**Comment by robbr48** [comment]
Good, I will test it. I noticed that it only happens occasionally, so it is hard to know for sure if the fix works.
