### ISSUE TITLE
Importing plot data fails if no model is open

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1830]
**Describe the bug**
Importing plot data with no model open causes crash

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Start Hopsan
2. Do not open a model
3. Call "repl" command from HCOM
4. The program will crash

**Expected behavior**
Either an error message, or as import orphan variables.

**Comment by peterNordin** [comment]
Hmm i fixed this previously for the gui buttons, (disable if no model open) but forgot the hcom command.
It is not possible to import if no model is open since there is no logdatahandler available then. It is not possible to share imported data between model, that would require redesign. So error message is the reasonable solution
