### ISSUE TITLE
HCOM: Cannot set quantity for all generations

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#1925]
**Describe the bug**
Set quantity only affects last generation, even when @* is appended to variable name.

**To Reproduce**
1. Load position servo example
2. Simulate twice
3. Execute `sequ GainP.out.y@* Position` in terminal
4. Only generation 2 of GainP.out.y get the Position quantity

**Expected behavior**
Both generation 1 and 2 should get the Position quantity

**Comment by peterNordin** [comment]
Preferably you set the quantity in the component properties before simulation, but yes, this should still be fixed

**Comment by peterNordin** [comment]
@robbr48 Hmm, I was looking to fix this, thought it would be an easy fix, but realized when I looked at the code that I deliberately did not allow to set quantity for all generations.
I think the reason was to avoid accidentally overwriting Quantity on old data. 

The intention was to set quantity in the model, so that any following simulations will create data variables with the actual correct Quantity. Changing quantity on a variable after you have created it should not be allowed at all I think. (Unless maybe if it is not already set)

What do you think ?

**Comment by robbr48** [comment]
I think it is more annoying not to be able to change quantity for old data than dealing with the risk of overwriting old quantities. You almost never want to have different quantities for different generations of the same variable anyway. Only reason I can think of is that you accidentally forget to set the quantity in the model, and then you would want to be able to fix it later.

**Comment by peterNordin** [comment]
I will allow this if you pass a "force" flag to the command

**Comment by peterNordin** [comment]
Actually I realized that the reason one could not set Quantity on old generations was a bug, the code to do it was there, so I just added support for @* or @a specifier as well. No force flag required.
