### ISSUE TITLE
PLOLookuptable not working

### ISSUE THREAD

**Issue by mrejster** [Hopsan/hopsan#1960]
PLOLookuptable not working

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Export data from some model using  >> sapl temp.plo x
2. Create a new model, containing the component PLOlookuptable
3. Try using the newly saved plo file...
4. The program will either: Be unable to open the file, Crash, or complain on the perfectly sorted "Time" vector used as input.

Expected behaviour: plo-files should work out-of-the box with this component.

**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Windows 10
 - Version: HopsanCore 64-bit, Version: 2.13.0.20191126.1813
                       HopsanGUI 64-bit, Version: 2.13.0.20191126.1813
 - Build: official.

**Additional information**
There might be an issue with how many lines the parser discards or the version number exported from hopsan.

**Comment by peterNordin** [comment]
@mrejster What is the "default plo export version" ? You can find it in options->plotting
Also is the file loaded from local disk or network drive ? (should not matter but useful to know)

**Comment by mrejster** [comment]
Ah, that's where the version could be changed!
Anyway, version 2 is malfunctioning. I now tried changing to plo version 1, and that seems to work as it should.

**Comment by peterNordin** [comment]
I tried this and also had problems with PLO v2 exported data. But I did not suffer from any crash (running Linux version). 
But I found a bug in the export code.
 In the "new" plo v2 format the fourth line containing numDataColumns and numRows, numDataColumns should also count the time vector, so if you export 'Time', 'X', 2048 samples, that line should say 2 2048. 
In PLO v1 format it says 1 2048. 

You could try to edit the plo v2 file after exporting it and just adding 1 to the first value on row 4.
Assuming the first column is Time. And see if that helps.

**Comment by peterNordin** [comment]
I just tried it myself, and it still does not work. 
But I know why, the parser assumes that the values on row six, are floating point, (plot scale) (wich are also not used by Hopsan). But in plo format 2 these values can be strings with the data Quantity (so in my test case it was "Time Position", which causes the rather unclear error about unsorted index vector. (because the parser will write 0 to every item due to this bug) 

So to fix that, also replace any strings with a numerical value 1.0 on row 6 in the plo version2 file. 

I wonder how I could even get this working when I implemented it many years ago, this code has not been touched in a long time. Probably never tested to export data including a Quantity.
