### ISSUE TITLE
Numbered equations in .md file

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1974]
**Is your improvement request related to a problem? Please describe.**
*I'm always frustrated when I add equations in the .md file and need to number the equations manually*

**Describe the solution you'd like**
*Equations should be numbered automatically. Also, it should be possible to add labels to be able to refer to the equations.*

**Additional context**
I understand that this may be related to the .md format and could therefore be off topic..

**Comment by peterNordin** [comment]
Yes that would be nice, but the equations are actually not part of the markdown format, but added as html comments that then get extracted from the generated html (generated from the md file) and processed to show a KaTeX equation (Javascript).
Not sure if KaTeX support labels and numbers, I will look and see, otherwise we could perhaps handle this in Hopsan somehow

**Comment by peterNordin** [comment]
@larsviktorlarsson  You can look here [https://katex.org/docs/support_table.html#e](https://katex.org/docs/support_table.html#e)
It links to two issues regarding numbered equations, its unclear to me if automatic equation number is solved yet, but they mention the `\tag{}` command. That puts a manual "number" far out to the right.

**Comment by peterNordin** [comment]
We could maybe make hopsan add such a tag for each EQUATION block, to auto number them. 
And to each EQUATION block add an optional LABEL=name part-
We could then maybe use REFEQUATION(label) in the markdown text, and auto replace that with the equation number.

But no clickable links, that is to complicated.
