### ISSUE TITLE
Crash when importing PLO files

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#2003]
**Describe the bug**
Hopsan crashes when exporting data to PLO and then trying to import the same file. I reads number of columns but then increases it by 1 for adding X-vector (time/frequency). However, the X-vector is already included in the number of columns number. As a result, it goes out of range and crashes.

**To Reproduce**
1. Plot something
2. Export to PLO
3. Improt same PLO file
4. The program will crash

**Expected behavior**
It should not crash :unamused: 

**Hopsan version (please complete the following information):**
Confirmed in Hopsan 2.15, probably related to latest PLO fixes.

**Additional information**
Example of erroneous PLO-file:

```
    'VERSION'
    2
    'plotest.PLO'
    3    2048
    'Time',    'Position_Sensor#out#Value',    'Step#out#Value'
  Time  Position  Position
  0.000000e+00  0.000000e+00  2.000000e-01
  1.500000e-03  6.999712e-09  2.000000e-01
  2.900000e-03  9.386945e-06  2.000000e-01
[...]
```
Example of correct PLO-file:

```
    'VERSION'
    2
    'plotest.PLO'
    2    2048
    'Time',    'Position_Sensor#out#Value',    'Step#out#Value'
  Time  Position  Position
  0.000000e+00  0.000000e+00  2.000000e-01
  1.500000e-03  6.999712e-09  2.000000e-01
  2.900000e-03  9.386945e-06  2.000000e-01
[...]
```

**Comment by peterNordin** [comment]
OK the problem here is that there are different implementations of plot importer in HopsanCore and GUI, and they both have a different idea about what PLO v2 means, according to a commit from 2015 I apparently postponed the introductions of actually using the correct value for the number of columns to PLO version 3, (which is still unfinished) but the HopsanCore PLO parser, did not change. Then in the fix made recently I "repaired" the export from the GUI so that the HopsanCore importer would work. 

But I think that the previous GUI version was the correct version, so I will restore that behavior in both GUI and Core
