### ISSUE TITLE
faild to generate moc_predefs.h

### ISSUE THREAD

**Issue by arthurx70** [Hopsan/hopsan#2022]
I try to compile hopsan with msvc use qt in wondows, but faild to generate moc_predefs.h.

Reading Qt configuration (C:/Qt/Qt5.14.2/5.14.2/msvc2017_64/bin/qmake)
1>Generate moc_predefs.h
1>generating debug/moc_predefs.h
1>C:\vs2019\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(209,5): error MSB6006: “cmd.exe” exit，code: 2。

Is there any suggest for this problem？

**Comment by peterNordin** [comment]
I dont know about that error in particular, but Hopsan does not yet fully support MSVC.
Only the core parts can be built, and they do not contain Qt code. So I am guessing that this comes from some GUI code on of the libraries based on QT.

I have a work-in-progress branch, https://github.com/Hopsan/hopsan/pull/2006, where I am trying to update the CMake build system so that it works for all Hopsan components. As a part of that work I will try to enable MSVC build as well, but it does not work at the moment. If you want to build on Windows you must currently use the MinGW compiler.

If you want to build using the official MinGW compiler included in the Qt installer, see this commit for example:
https://github.com/Hopsan/hopsan/pull/1876/commits/91c6258dc6817a81a7864a58883d863c37616af9

**Comment by arthurx70** [comment]
thank you peterNordin,I use MSVC with vs2019 +Qt5.14.2,build both core and GUI are succeed.the problem I asked disappeared when I reopen solution in vs2019.

**Comment by peterNordin** [comment]
@arthurx70 I have now added semi-official support for MSVC using CMake. Also there have been a lot of fixes of MSVC build related problems in various parts of Hopsan. Hopefully this may be helpful for you as well, even if you apparently were already able to build using MSVC. 

Some work still remains to enable all functionality using MSVC.
