### ISSUE TITLE
Terminal Window : Simulation Error / Red Flash Timing

### ISSUE THREAD

**Issue by OwenDavid** [Hopsan/hopsan#2028]
In the event of a simulation error two things happen,

1. The error message is printed to the terminal in a red font
2. There is a red flash to the terminal background which fades over time.

The combination of the red font and red flash make it impossible to read the error message until the flash has faded. The flash seems that it takes a long time to fade after an error has occurred and you are waiting to read the message...

**Describe the solution you'd like**

The ability to read the error message instantly please.

Suggestions,

1.  Reduce time of red flash fade
2.  Change red flash color so the error message font is readable sooner
3.  Consider flashing the simulation background instead with a lighter color
4. Put an error widget on the terminal button strip and animate this

**Comment by robbr48** [comment]
I am not really able to reproduce the problem. I do get the red flash, but it fades quickly and the error is readable almost instantly. I wonder if this behavior is platform dependent? What is your operating system?

Reducing the fading time should be possible. I want the color to be red though, to clearly indicate that an error has occurred. I also want it to appear in the terminal window. The reason we added this was that many users missed the error messages, since they didn't notice the terminal output.

According to the source code the fading should only take 0.93 seconds, but it clearly takes longer even for me. There could be something wrong with the implementation. Perhaps a solution could be to remove the fading, and instead just make the background red for a short fixed time period. This would require far fewer events to be triggered.
