### ISSUE TITLE
HCOM Autocomplete drives me nuts!

### ISSUE THREAD

**Issue by mrejster** [Hopsan/hopsan#2053]
**Is your improvement request related to a problem? Please describe.**

Autocomplete is a great function in HCOM. But it should be activated using a key (=TAB) not add whatever it finds suiting when pressing enter. In the case below, I wish to get the 1st generation. But if pressing enter at this stage I get the "102mm_90513810.A1" 'th generation, which doesn't even make sense. Unless I press space before enter, but this is not natural for my muscle memory from most other software, and I constantly find myself having to erase long autocompleted lines.
 
![image](https://user-images.githubusercontent.com/6499803/105464230-7f425900-5c91-11eb-9bcf-edad409e60b6.png)

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*
Activation of autocomplete with TAB key (as is the case already), but NOT by default when pressing enter.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered. (optional)*

**Additional context**

**Comment by peterNordin** [comment]
yes its annoying

**Comment by peterNordin** [comment]
I tried disabling enter for auto complete, and while it works, I do not like it in the case where you actually use the keyboard keys to select a completion in the list. In that case I expect enter to activate my choice.
But I did find an other solution to this problem in particular, if @ is in front of the word to be completed, the completion popup is not activated.  That solves this problem in particular.
@mrejster What do you think about that solution ?

It would also be possible to add a completion box for the generation numbers, but I dont know how useful that would be.
Possibly there are other cases as well when this annoyance happens, but they may be solvable in a similar way.

It would be possible to add a configuration option for the Enter/Return button activation if you feel very strongly about it :)

**Comment by mrejster** [comment]
Hi,

Though your solution would solve the particular problem, I believe it would
be better if the list doesn't appear by default at all.
Using enter for autocomplete when selecting in the list is fine, enter
should definitely select the choice, but I think it is better if the entire
list doesn't show up by default.

Proposed functionality:
"a" "+" "b" "<enter>" should give the result a+b evaluates to.
Today, it gives (in my particular model)
a+bar_1.A.y
since "b" is autocompleted by default when striking enter.

Instead, the autocomplete list should appear when doing this:
"a" "+" "b" "<tab>"
then selection is done using arrows + <enter> as today.

I think this solves all cases, and makes the behaviour much more similar to
(for example) matlab.

//Erik


Den fre 22 jan. 2021 kl 23:04 skrev Peter Nordin <notifications@github.com>:

**Comment by peterNordin** [comment]
OK, I can see your problem. Unfortunately this was not as easy to solve as I thought. I am considering a quick-fix before version 2.17. And then we can try to solve it properly after that.

I made a new quick-fix, that no longer auto selects the first item in the list that shows up. Then when you press enter the autocomplete list will just close since no selection has been made. You have to select with the mouse or keyboard arrows before pressing enter/tab to get autocomplete.

This means that if you dont want autocomplete, just press enter twice, of course this is also annoying, but slightly less then before.

@robbr48  What do you think? I also found that there seem to be two different sets of code for auto-complete. One using the QCompleter (the one used now) and some other (older?) code that used to active on pressing the tab key. But that code never runs now, since the QCompleter dialog takes over.

**Comment by mrejster** [comment]
ok!. The quick fix is not so important, as long as the long term result is
good.

Thanks!

Den tis 26 jan. 2021 kl 23:30 skrev Peter Nordin <notifications@github.com>:

**Comment by robbr48** [comment]
At first I did not want the user to press a key for the autocompleter to appear, because most users would then not realize that this function exists. But maybe it is still a better way. Matlab for example uses the `tab` key to open the list. Qt Creator does not require a key press, but it is also less of a problem in a code editor where you don't execute commands with `enter`. I think we should add a key press requirement, and maybe add a tooltip or other help text that informs the user of the function.

But there are two problems here I think. One is that the list appears even when you don't want it. The second problem is that the autocompleter suggestions does not take the preceeding text into account. It should never automcomplete to `chpv pfp@102mm_90513810.A1`, since that is not a legal generation. Autocompleting from `chpv pfp@` should only show available genreations in the pfp variable in the list. Unfortunately this is far more complicated, since it requires us to parse the preceeding text and figure out what it means.

**Comment by mrejster** [comment]
I agree completely on the first part.
However, the usefulness of autocompleting generations is limited, since
they are typically 1 digit or 2 only. And one still has to keep track of
what generation is what anyway.

//Erik

Den ons 27 jan. 2021 kl 08:31 skrev robbr48 <notifications@github.com>:

**Comment by peterNordin** [comment]
@mrejster I think that I have fixed the most annoying cases, please see the description of the changes in the linked pull-request and comment if you like.
@robbr48 It would be very good if you could test this. I have done some testing myself, but I have likely missed some special case. Maybe you can find one.
