### ISSUE TITLE
Possible error in SignalPID2

### ISSUE THREAD

**Issue by robbr48** [Hopsan/hopsan#2080]
Maybe I'm mistaken here, but I think this is wrong. If the derivative input is not connected, the derivative is approximated according to the following code:
```
if (mUseDeInput)
{
    dErr = (*mpDerr);
}
else
{
    dErr = err-mLastErr;
    mLastErr = err;
}
```
Should not dErr be divided by mTimestep in the second case?

**Comment by peterNordin** [comment]
Hmm, I think I based that code on some Digital Control Theory course material. Which I probably have in some box in the attic.
But if I compare with the "standard form" in the https://en.wikipedia.org/wiki/PID_controller article it seems to be the one I am using.

I think the division with timestep comes on line 123, so `dErr` is actually "delta error". But if this is true, then the bug is in the description of the `dE`, input variable. It say `Derivative signal input` which is then wrong, (it should be delta error).

But maybe a different calculation should be used in that case, where the division with time step is not done (since it is assumed to be part of the input signal). But maybe moving the division with timestep into line 114 `dErr = (err-mLastErr)/mTimestep` is better in that case. Then `dE` would still be error derivative and the case where `dE` is not used will still calculate the same result.

Not sure what is the most convenient for the input signal. But now when I think about it, the description is a bit unclear anyway.
`Derivative signal input` Derivative of what?


But I would like a second/third opinion in this case. It was so long ago I made this.

**Comment by robbr48** [comment]
I think the input variable should be the derivative and not the "delta error". Otherwise the user would need to compute the delta error using signal components, which is quite complicated. So moving the division to line 114 is the best solution in my opinion.

According to Wikipedia it should be the derivative of the error signal. It is quite common to use the derivative of the feedback signal though, to avoid "derivative kicks" due to sudden changes in the reference value (explained [here](https://apmonitor.com/pdc/index.php/Main/ProportionalIntegralDerivative). The problem is that the derivative of the feedback signal has the opposite sign of the error signal. 

In order words, we need to decide whether we should use the derivative of the feedback or the error signal. Using the error signal may cause derivative kicks. Using the feedback signal does not conform with the "standard" PID form, although it is commonly used in industry. I vote for the latter alternative.
