### ISSUE TITLE
Hopsan Export FMU Crash

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#2100]
**Describe the bug**
*Hopsan crashes when trying to export FMU.*

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Start Hopsan
2. Open model FMI_lek.hmf (provided)
3. Choose "Create Functional Mocup Unit" -> FMU 2.0 (32-bit)
4. Choose folder
5. Compiler starts but then exits with: "
Makefile:25: recipe for target 'defaultComponentLibraryInternal.o' failed

In file included from componentLibraries/defaultLibrary/defaultComponentLibraryInternal.cpp:36:0:
componentLibraries/defaultLibrary/Components.h:27:64: fatal error: Electric/Controllers&Switches/Controllers&Switches.h: No such file or directory
compilation terminated.
bin\mingw32-make.exe: *** [defaultComponentLibraryInternal.o] Error 1
bin\mingw32-make.exe: *** Waiting for unfinished jobs....

File 'C:/Users/572098/OneDrive - parkercorp/Documents/FMI/fmu-stage/binaries/win32/FMI_lek.dll' not found in directory ''

**Expected behavior**
*A working FMU unit should be generated.*

**Screenshots, Model or Data files**
![image](https://user-images.githubusercontent.com/62874593/137338623-32ed4ca7-27dd-40e1-a6be-e68c6d9e64a8.png)
[FMI_lek.zip](https://github.com/Hopsan/hopsan/files/7346833/FMI_lek.zip)

**Hopsan version:**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS:  Windows 10
 - Version:  HopsanCore 32-bit, Version: 2.19.0.20210510.2046
                       HopsanGUI 32-bit, Version: 2.19.0.20210510.2046
 - Build: Is this an **official** build downloaded from the web page**

**Additional information*

*

**Comment by peterNordin** [comment]
This is depressing, I think I know what the problem is (it is in packaging) but that would mean that FMU export has not worked for the at least 6 years, maybe longer. I am not sure though, has really no one detected this until now.

We always run development snapshots, so of course we do not notice this. Also all automated tests run before packaging. 

I think I tried to fix a related problem about 4 years ago according to the logs.
To allow "dirty" files (re-generated during build) to be added during packaging, but I realize now that it did not take into account, "new files" that were auto generated, they were discarded. 
This is caused by our reliance on "svn export" behavior from git, which I hacked togetheter. 

I think that it is finally time to get rid of it, I did on Linux, but Windows is always more complicated to deal with.
